- name: setting locale
  locale_gen:
    name: "{{ system_locale }}"
    state: present

- name: install sudo
  apt:
    name: sudo
    state: present

- name: installing dependencies (bullseye)
  apt:
    pkg: ['postgis', 'postgresql-13-postgis-3', 'postgresql-13-postgis-3-scripts', 'postgresql-contrib']
    state: present
    update_cache: yes
  when: ansible_distribution_release == "bullseye"
# postgresql-11-postgis-2.5-scripts #for postgis.control
# postgresql-contrib #for dblink extension

- name: install python-psycopg2 for ansible psql modules (bullseye)
  apt:
    name: python3-psycopg2
    state: present
  when: ansible_distribution_release == "bullseye"

- name: create georchestra user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ georchestra.db.user }}"
    password: "{{ georchestra.db.pass }}"
    encrypted: yes

- name: create georchestra main database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ georchestra.db.name }}"
    owner: "{{ georchestra.db.user }}"
    template: template0
    encoding: UTF8

- include: geonetwork.yml
  become: yes
  become_user: postgres
  tags: postgresql_geonetwork

- include: geofence.yml
  become: yes
  become_user: postgres
  tags: postgresql_geofence

- include: other_schemas.yml
  become: yes
  become_user: postgres
  tags: postgresql_other_schemas

- include: cadastrapp.yml
  tags: postgresql_cadastrapp
  when: cadastrapp.enabled

- include: clean.yml
  tags: [cleanup, postgresql_cleanup]
  when: cleanup is defined
