---
- name: remove wars
  apt:
    pkg: "{{ item.value.pkg }}"
    state: absent
    purge: true
  with_dict: "{{ georchestra_wars }}"
  when: item.value.pkg is defined and item.value.enabled
# roles/tomcat/tasks/clean.yml already removed the unzipped wars

- name: remove datadirs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ geonetwork.datadir.path }}"
    - "{{ geoserver.datadir.path }}"
    - "{{ geowebcache_datadir }}"
    - "{{ georchestra.datadir.path }}"

- name: remove non-free and contrib for dependencies (bullseye)
  apt_repository:
    repo: deb http://ftp.fr.debian.org/debian/ bullseye main non-free contrib
    state: absent
  when: ansible_distribution_release == "bullseye"
