- name: install datafeeder package
  apt:
    pkg: georchestra-datafeeder
    state: latest

- name: setup a systemd unit file
  template:
    src: "datafeeder/datafeeder.service.j2"
    dest: "/etc/systemd/system/datafeeder.service"
  register: df_unitfile

- name: start/enable the datafeeder service
  systemd:
    state: restarted
    daemon_reload: yes
    name: datafeeder
  when: df_unitfile.changed
