- name: configures the datafeeder part of the datadir
  debug:
    msg: "not implemented yet (provided by PR georchestra/datadir#211)"

- name: installs datafeeder.jar (backend)
  get_url:
    url: https://packages.georchestra.org/datafeeder/datafeeder.jar
    dest: /opt/datafeeder.jar
    mode: '0644'

- name: setup a systemd unit file
  template:
    src: "datafeeder/datafeeder.service.j2"
    dest: "/etc/systemd/system/datafeeder.service"
  register: df_unitfile

- name: restart sword service
  systemd:
    state: restarted
    daemon_reload: yes
    name: datafeeder
  when: df_unitfile.changed

- name: installs the datafeeder-ui (frontend) in the 'georchestra' tomcat
  get_url:
    url: https://packages.georchestra.org/datafeeder/import.war
    dest: /srv/tomcat/georchestra/webapps/import.war
    mode: '0644'
