- name: checkout geonetwork datadir
  become: yes
  become_user: tomcat
  git:
    dest: "{{ geonetwork.datadir.path }}"
    repo: "{{ geonetwork.datadir.gitrepo }}"
    version: "{{ geonetwork.datadir.gitversion }}"
    force: yes
