---
- name: install the gn-cloud-searching microservice
  get_url:
    url: "{{ gn_cloud_searching.url }}"
    dest: /usr/share/lib/searching.jar

- name: templating a configuration file
  tags: config
  template:
    src: geonetwork/gn-cloud-searching-application.yml.j2
    dest: /etc/georchestra/geonetwork/microservices/searching/config.yml

- name: setup a systemd unit file
  tags: systemd
  template:
    src: geonetwork/gn-cloud-searching.service.j2
    dest: /etc/systemd/system/gn-cloud-searching.service
  register: gn_cloud_searching_unitfile

- name: start/enable the gn-cloud-searching service
  tags: systemd
  systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: gn-cloud-searching
  when: gn_cloud_searching_unitfile.changed
