- name: install the gn-cloud-searching microservice
  get_url:
    url: "{{ gn_cloud_searching.url }}"
    dest: "/usr/share/lib/georchestra-gn-cloud-searching.zip"
    headers:
      Authorization: "Bearer {{ github_action_token }}"

- name: unzips the war
  unarchive:
    src: "/usr/share/lib/georchestra-gn-cloud-searching.zip"
    dest: /usr/share/lib
    remote_src: yes

- name: removes the downloaded archive
  file:
    path: "/usr/share/lib/georchestra-gn-cloud-searching.zip"
    state: absent

- name: prepare a configuration directory for the microservice
  file:
    path: "/etc/georchestra/geonetwork/microservices/searching"
    state: directory

- name: templating a configuration file
  template:
    src: "geonetwork/gn-cloud-searching-application.yml.j2"
    dest: "/etc/georchestra/geonetwork/microservices/searching/application.yml"



- name: setup a systemd unit file
  template:
    src: "geonetwork/gn-cloud-searching.service.j2"
    dest: "/etc/systemd/system/gn-cloud-searching.service"
  register: gn_cloud_searching_unitfile

- name: start/enable the datafeeder service
  systemd:
    state: restarted
    daemon_reload: yes
    name: gn-cloud-searching
  when: gn_cloud_searching_unitfile.changed
