- name: create datadirs
  tags: wars
  file:
    path: "{{ item }}"
    state: directory
    owner: tomcat8
    group: tomcat8
  with_items:
  - "{{ geonetwork.datadir.path }}"
  - "{{ geoserver.datadir.path }}"
  - "{{ geowebcache_datadir }}"
  - "{{ extractor_datadir }}"

- include: config.yml
  tags: config

- include: war_cadastrapp.yml
  tags: cadastrapp_war
  when: cadastrapp.enabled

- include: geoserver.yml
  tags: geoserver

- include: geonetwork.yml
  tags: geonetwork

- include: wars.yml
  tags: wars

- name: force-disable recaptcha check
  tags: fucaptcha
  blockinfile:
    dest: "{{ tomcat_basedir }}/{{ georchestra_wars['console']['tomcat'] }}/webapps/console/WEB-INF/views/validation.jsp"
    marker: '//ansible disable recaptcha'
    insertafter: '	removeError\("g-recaptcha"\);'
    content: |
      document.form.recaptcha_response_field.value='nothankyou';
      return true;

  when: console_captcha.privateKey == ''

- include: nativelibs.yml
  tags: nativelibs

- include: cadastrapp.yml
  tags: cadastrapp_addon
  when: cadastrapp.enabled

- include: clean.yml
  tags: [cleanup, georchestra_cleanup]
  when: cleanup is defined
