- name: enable non-free and contrib for dependencies (buster)
  apt_repository:
   repo: "deb http://deb.debian.org/debian buster main contrib"
  when: ansible_distribution_release == "buster"

- name: enable non-free and contrib for dependencies (bullseye)
  apt_repository:
   repo: "deb http://deb.debian.org/debian bullseye main contrib"
  when: ansible_distribution_release == "bullseye"

- name: install runtime dependencies (buster)
  apt:
    pkg: [ ttf-mscorefonts-installer, gdal-bin, libgdal-java ]
    state: present
  when: ansible_distribution_release == "buster"

# libgdal-java does not exist anymore in bullseye
# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=947960
- name: install runtime dependencies (bullseye)
  apt:
    pkg: [ ttf-mscorefonts-installer, gdal-bin ]
    state: present
  when: ansible_distribution_release == "bullseye"

#- name: fetch libjpeg-turbo deb from sourceforge
#  get_url: dest=/tmp/ url=http://sourceforge.net/projects/libjpeg-turbo/files/1.4.0/libjpeg-turbo-official_1.4.0_amd64.deb

#- name: install libjpeg-turbo deb
#  apt: deb=/tmp/libjpeg-turbo-official_1.4.0_amd64.deb

- name: point georchestra's shared.loader to catalina.base/shared/*.jar
  lineinfile:
    dest: "{{ tomcat_basedir }}/georchestra/conf/catalina.properties"
    regexp: 'shared.loader=${catalina.home}/shared/classes,${catalina.home}/shared/*.jar,/var/lib/tomcat9/shared/classes,/var/lib/tomcat9/shared/*.jar'
    line: 'shared.loader=${catalina.home}/shared/classes,${catalina.base}/shared/*.jar,/var/lib/tomcat9/shared/classes,/var/lib/tomcat9/shared/*.jar'

- name: create tomcat shared dir
  file:
    dest: "{{ tomcat_basedir }}/georchestra/shared/"
    state: directory

- name: symlink gdal.jar to tomcat shared dir
  file:
    src: /usr/share/java/gdal.jar
    dest: "{{ tomcat_basedir }}/georchestra/shared/gdal.jar"
    state: link
  when: ansible_distribution_release == "buster"

- name: hardlink gdal.jar to geoserver libdir
  file:
    src: /usr/share/java/gdal.jar
    dest: "{{ tomcat_basedir }}/geoserver/webapps/geoserver/WEB-INF/lib/gdal.jar"
    state: hard
  when: ansible_distribution_release == "buster"

#- name: remove conflicting imageio-ext-gdal-bindings jar
#  file: path={{ tomcat_basedir }}/geoserver/webapps/geoserver/WEB-INF/lib/imageio-ext-gdal-bindings-1.9.2.jar state=absent
