---
- name: copy cadastrapp deb
  check_mode: false
  synchronize:
    src: "{{ cadastrapp.debsrc.path }}/{{ cadastrapp.debsrc.pkg }}"
    dest: /tmp/{{ cadastrapp.debsrc.pkg }}
  delegate_to: "{{ cadastrapp.debsrc.host }}"

- name: install cadastrapp deb
  apt:
    deb: /tmp/{{ cadastrapp.debsrc.pkg }}
    state: present

- name: remove deb
  file:
    path: /tmp/{{ cadastrapp.debsrc.pkg }}
    state: absent
