- name: add the ResourceLink for jdbc/cadastrapp
  lineinfile:
    dest: "{{ tomcat_basedir }}/georchestra/conf/context.xml"
    insertbefore: '</Context>'
    line: '<ResourceLink name="jdbc/cadastrapp" global="jdbc/cadastrapp" type="javax.sql.DataSource"/>'
    state: present

- name: symlink postgresql.jar for jdbc/cadastrapp
  file:
    src: "{{ tomcat_basedir }}/georchestra/webapps/cadastrapp/WEB-INF/lib/postgresql-9.4-1205-jdbc4.jar"
    dest: /usr/share/tomcat9/lib/postgresql-9.4-1205-jdbc4.jar
    state: link
