- name: create instance {{ item.key }}
  command: tomcat8-instance-create -p {{ item.value.port }} -c {{ item.value.control_port }} {{ tomcat_basedir }}/{{ item.key }} creates={{ tomcat_basedir }}/{{ item.key }}
  with_dict: "{{ tomcat_instances }}"

- name: symlink policy.d dir
  file:
    src: /etc/tomcat8/policy.d/
    dest: "{{ tomcat_basedir }}/{{ item }}/conf/policy.d"
    state: link
  with_items: "{{ tomcat_instances.keys() }}"

- name: recursively fix dirs ownership
  file:
    name: "{{ tomcat_basedir }}/{{ item.0 }}/{{ item.1 }}"
    state: directory
    recurse: yes
    owner: tomcat8
  with_nested:
    - "{{ tomcat_instances.keys() }}"
    - [ logs, temp, conf, work, webapps ]

- name: install instance config in /etc/default
  template:
    src: "config-{{ item }}.j2"
    dest: "/etc/default/tomcat-{{ item }}"
  with_items: "{{ tomcat_instances.keys() }}"

- name: install instance connector
  template:
    src: "server-{{ item }}.xml.j2"
    dest: "{{ tomcat_basedir }}/{{ item }}/conf/server.xml"
  with_items: "{{ tomcat_instances.keys() }}"

- name: enable instance
  service:
    name: "tomcat-{{ item }}"
    enabled: yes
  with_items: "{{ tomcat_instances.keys() }}"
