---
- import_tasks: common.yml
- import_tasks: instance.yml
- import_tasks: cadastrapp.yml
  when: cadastrapp.enabled
- import_tasks: clean.yml
  tags: [cleanup, tomcat_cleanup]
  when: cleanup is defined
